services:
  - type: web
    name: house-price-prediction
    env: python
    region: oregon    # You can change the region if needed (e.g., frankfurt)
    buildCommand: 
      - pip install -r requirements.txt
    startCommand: 
      - gunicorn app:app --workers 4 --threads 2 --bind 0.0.0.0:$PORT
    autoDeploy: true
    envVars:
      - key: FLASK_ENV
        value: production
    pythonVersion: 3.9
